version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - model-data:/app/model
    env_file:
      - .env
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s

volumes:
  model-data:
    external: true
